### ISSUE TITLE
Testing issues

### ISSUE THREAD

**Issue by JosefButts** [learn-co-curriculum/javascript-first-class-functions-lab#10]
My tests are failing , yet when the lesson page states that I completed the lab successfully. I don't know what's going on, I am writing and testing each function one at a time, it isn't giving me errors beyond the following:

1)  "before all" hook:                                                                                                                                                   
     Error: timeout of 1000ms exceeded. Ensure the done() callback is being called in this test.                                                                           
      at Object.done (node_modules/mocha-jsdom/index.js:70:7)                                                                                                              
      at process.nextTick (node_modules/jsdom/lib/jsdom.js:325:18)                                                                                                         
      at _combinedTickCallback (internal/process/next_tick.js:73:7)                                                                                                        
      at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by gj** [comment]
Hi @CodeforJoe !

[Here's a great article](http://help.learn.co/workflow-tips/errors/error-timeout-of-2000ms-exceeded) in the [Learn Help Center](http://help.learn.co/) about this very issue. 🙂
